In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
from sklearn_extra.cluster import KMedoids

In [2]:
import pandas as pd

# Display all columns
pd.set_option('display.max_columns', None)

# Display all rows
pd.set_option('display.max_rows', None)

In [3]:
def get_branch_rank(branch_id):
    branch_dict = {1: [218, 354, 356, 318, 346, 953, 121, 310, 9], 2: [10, 958, 328, 1038, 957, 811], 3: [92, 89, 48, 345], 4: [21, 339, 340, 802, 351], 5: [224, 135], 6: [60], 7: [956, 134], 8: [11, 1042], 9: [1007], 10: [326], 11: [86], 12: [124, 125], 13: [903], 14: [801], 15: [75, 952], 16: [99], 17: [85, 91], 18: [97], 19: [17], 20: [959], 21: [70], 22: [108], 23: [1001], 24: [33], 25: [5], 26: [101], 27: [132], 28: [128], 29: [902], 30: [348], 31: [51, 114], 32: [131], 33: [120], 34: [36], 35: [15, 68], 36: [102], 37: [109], 38: [90], 39: [103], 40: [20], 41: [59], 42: [130], 43: [78], 44: [117], 45: [58], 46: [904], 47: [96], 48: [119], 49: [113], 50: [123], 51: [126], 52: [53], 53: [7], 54: [77], 55: [39], 56: [84], 57: [35], 58: [1013], 59: [57], 60: [47], 61: [112], 62: [14], 63: [18], 64: [2], 65: [115], 66: [25], 67: [129], 68: [116], 69: [347], 70: [55], 71: [87], 72: [1], 73: [26], 74: [110], 75: [100], 76: [331], 77: [62], 78: [56], 79: [8], 80: [122], 81: [16], 82: [350], 83: [1015], 84: [31], 85: [962], 86: [118], 87: [111], 88: [106], 89: [88], 90: [52], 91: [3], 92: [42], 93: [105], 94: [1003], 95: [63], 96: [1008], 97: [40], 98: [76], 99: [46], 100: [83], 101: [43], 102: [34], 103: [79], 104: [810], 105: [72], 106: [61], 107: [32], 108: [37], 109: [45], 110: [4]}
    for rank,branches in branch_dict.items():
        if(branch_id in branches):
            return rank

def get_optimal_cluster(category):
    grouped_data = filtered.groupby('cluster')
    cat_positions = pd.DataFrame(columns=['cat_rank','top_branch'],index=[0,1,2,3,4,5,6])
    for i,df in grouped_data:
        x = list(df['consolidated_category'].value_counts().sort_values(ascending=False).index).index(category)
        top_branch = list(df['issue_branch_id'].value_counts().sort_values(ascending=False).index)[0]
        cat_positions.at[i,'cat_rank'] = x
        cat_positions.at[i,'top_branch'] = get_branch_rank(top_branch)
    
    cat_positions.sort_values(by=['cat_rank','top_branch'],ascending=[True,False],inplace=True)
    return list(cat_positions.index)

def get_user_cluster(category,filtered):
    optimal_cluster = get_optimal_cluster(category)[0]
    return filtered[filtered['cluster']==optimal_cluster]

In [4]:
filtered=pd.read_csv("clustered_og_data.csv")

In [5]:
filtered["consolidated_category"].unique()

array(['Non Fiction', 'Teens', 'Self Help', 'Fiction', 'Kids', 'GK',
       'Languages', 'Entertainment'], dtype=object)

In [6]:
filtered.drop(columns=["Unnamed: 0"],inplace=True)

In [9]:
x = get_user_cluster('Teens',filtered)

In [11]:
x.head(100)

,# unique_id,created_at,branch_name,creation_date,last_modified_date,Book_Type,ibt_id,issue_branch_id,issue_date,member_branch_id,return_date,return_branch_id,subscription_id,book_id,title_id,number,Book_Sharable,book_status,branch_id,orig_branch_id,book_title,active,membership_expirydate,member_card,num_books,num_magazine,sec_deposit,start_date,year,consolidated_category,cluster
10,4.000000e+13,60,MASTER WAREHOUSE-2,01-01-2017 10:53,01-01-2017 10:53,BOOK,0,60,01-01-2017,60,07-01-2017,60,1318317,3963952,345428,837784,Yes,RENTED,1008,962,THE JOURNEY THROUGH TIME,0,31-01-2017 12:00,M165196,2.0,0,500,31-03-2016 12:00,2017,Kids,1
11,4.000000e+13,37,MASTER WAREHOUSE-2,01-01-2017 05:10,01-01-2017 05:10,BOOK,0,37,01-01-2017,37,11-01-2017,37,1452724,3961255,205075,835746,Yes,TRANSIT,962,962,GERONIMO STILTON #46 THE HAUNTED CASTLE,1,05-12-2021 13:28,M178193,4.0,0,0,27-11-2016 12:00,2017,Kids,1
14,4.000000e+13,31,MASTER WAREHOUSE-2,01-01-2017 10:03,01-01-2017 10:03,BOOK,0,31,01-01-2017,31,08-01-2017,31,1091884,4098673,271387,954322,Yes,RENTED,1015,962,HEROES OF OLYMPUS : THE LOST HERO,0,13-08-2017 12:00,M097067,2.0,1,500,13-01-2013 12:00,2017,Teens,1
17,4.000000e+13,32,MASTER WAREHOUSE-2,01-01-2017 05:23,01-01-2017 05:23,BOOK,0,32,01-01-2017,32,01-01-2017,32,1330795,4028784,196832,889359,Yes,RENTED,962,962,GERONIMO STILTON #33 GERONIMO AND THE GOLD MED...,0,21-12-2017 12:00,M174600,2.0,1,500,21-04-2016 12:00,2017,Kids,1
29,4.000000e+13,33,MASTER WAREHOUSE-2,01-01-2017 05:39,01-01-2017 05:39,BOOK,0,33,01-01-2017,33,08-01-2017,33,1386262,3887561,320057,779066,Yes,RENTED,962,962,DIARY OF A WIMPY KID: THE THIRD WHEEL,0,19-07-2017 12:00,M176452,2.0,1,500,19-07-2016 12:00,2017,Teens,1
34,4.000000e+13,60,MASTER WAREHOUSE-2,01-01-2017 05:26,01-01-2017 05:26,BOOK,0,60,01-01-2017,60,04-01-2017,60,1063906,3656978,191079,584358,Yes,TRANSIT,227,962,ARTEMIS FOWL,0,14-06-2017 12:00,M079892,2.0,0,500,14-08-2012 12:00,2017,Teens,1
40,4.000000e+13,3,Pune - Sinhagad Road,01-01-2017 08:01,01-01-2017 08:01,BOOK,0,3,01-01-2017,3,15-01-2017,3,1185482,4060925,366622,918166,Yes,AVAILABLE,79,79,NUTTY AND BIRDIES,1,12-04-2020 12:00,M129611,2.0,0,500,09-04-2014 12:00,2017,Kids,1
118,4.000000e+13,77,Mantri Lithos Apartments,01-01-2017 11:14,01-01-2017 11:14,BOOK,0,77,01-01-2017,77,15-01-2017,77,13854,3933622,222368,815479,Yes,AVAILABLE,324,324,LITTLE WITCHS BIG NIGHT: STEP INTO READING STEP 3,0,06-05-2017 12:00,M012116,3.0,0,0,06-06-2010 12:00,2017,Kids,1
120,4.000000e+13,52,HW Murgeshpalya,01-01-2017 07:34,01-01-2017 07:34,BOOK,0,52,01-01-2017,52,10-02-2017,52,1283294,3607371,169171,537560,Yes,AVAILABLE,139,139,ENCHANTED WORLD - MELODY AND THE GEMINI LOCKET,1,13-03-2019 12:00,M161630,4.0,1,0,12-09-2015 12:00,2017,Teens,1
164,4.000000e+13,32,AECS Layout,01-01-2017 12:11,01-01-2017 12:11,BOOK,0,32,01-01-2017,32,03-01-2017,32,1138727,4078774,363513,938445,Yes,RENTED,32,32,FIVE KINGDOMS : CRYSTAL KEEPERS,0,09-10-2017 12:00,M113494,10.0,0,0,09-08-2013 12:00,2017,Teens,1
174,4.000000e+13,32,AECS Layout,01-01-2017 05:23,01-01-2017 05:23,BOOK,0,32,01-01-2017,32,01-01-2017,32,1330795,3992863,351238,860133,Yes,AVAILABLE,32,32,GERONIMO STILTON - CAVEMICE#05 THE GREAT MOUSE...,0,21-12-2017 12:00,M174600,2.0,1,500,21-04-2016 12:00,2017,Kids,1
177,4.000000e+13,32,AECS Layout,01-01-2017 06:40,01-01-2017 06:40,BOOK,0,32,01-01-2017,32,07-01-2017,32,1150241,3971604,196836,843506,Yes,TRANSIT,1008,32,GERONIMO STILTON #40 THE KARATE MOUSE,1,25-09-2019 12:42,M181837,2.0,0,0,04-10-2013 12:00,2017,Kids,1
178,4.000000e+13,32,AECS Layout,01-01-2017 03:21,01-01-2017 03:21,BOOK,0,32,01-01-2017,1,01-01-2017,32,1459033,3912065,195943,798068,Yes,AVAILABLE,32,32,ATTACK OF THE BANDIT CATS,1,31-01-2023 00:00,M180597,1.0,0,500,11-12-2016 12:00,2017,Kids,1
179,4.000000e+13,32,AECS Layout,01-01-2017 03:22,01-01-2017 03:22,BOOK,0,32,01-01-2017,1,08-01-2017,32,1459033,3912065,195943,798068,Yes,AVAILABLE,32,32,ATTACK OF THE BANDIT CATS,1,31-01-2023 00:00,M180597,1.0,0,500,11-12-2016 12:00,2017,Kids,1
187,4.000000e+13,32,AECS Layout,01-01-2017 07:55,01-01-2017 07:55,BOOK,0,32,01-01-2017,32,04-01-2017,32,1467323,4013369,348782,876306,Yes,RENTED,32,32,MY FIRST BOOK - 123,0,01-01-2018 12:00,M183263,2.0,0,0,01-01-2017 12:00,2017,Kids,1
191,4.000000e+13,32,AECS Layout,01-01-2017 08:01,01-01-2017 08:01,BOOK,0,32,01-01-2017,32,03-01-2017,32,1330795,3791580,68777,701218,Yes,AVAILABLE,32,32,RAINBOW MAGIC: THE PARTY FAIRIES: 19: POLLY TH...,0,21-12-2017 12:00,M174600,2.0,1,500,21-04-2016 12:00,2017,Kids,1
200,4.000000e+13,32,AECS Layout,01-01-2017 03:22,01-01-2017 03:22,BOOK,0,32,01-01-2017,1,08-01-2017,32,1459033,4028782,196133,889377,Yes,RENTED,32,32,THE MOUSE ISLAND MARATHON,1,31-01-2023 00:00,M180597,1.0,0,500,11-12-2016 12:00,2017,Teens,1
268,4.000000e+13,32,AECS Layout,01-01-2017 05:05,01-01-2017 05:05,BOOK,0,32,01-01-2017,32,11-02-2017,32,57394,1790476,196128,391678,Yes,AVAILABLE,32,32,THE SEARCH FOR SUNKEN TREASURE,1,21-09-2021 16:44,M048079,2.0,0,0,27-10-2011 12:00,2017,Teens,1
272,4.000000e+13,32,AECS Layout,01-01-2017 03:39,01-01-2017 03:39,BOOK,0,32,01-01-2017,32,08-01-2017,1,1085580,1517111,245536,211478,Yes,AVAILABLE,32,32,THE WISE RABBIT,1,14-03-2020 12:00,M096966,2.0,1,500,13-12-2012 12:00,2017,Kids,1
274,4.000000e+13,32,AECS Layout,01-01-2017 05:15,01-01-2017 05:15,BOOK,0,32,01-01-2017,4,19-02-2017,4,1254924,1545290,127777,241189,Yes,AVAILABLE,32,32,HIGH SCHOOL MUSICAL - FRIEND FOREVER (7) - 978...,0,05-07-2018 12:00,M152698,3.0,0,500,05-05-2015 12:00,2017,Kids,1
275,4.000000e+13,32,AECS Layout,01-01-2017 04:06,01-01-2017 04:06,BOOK,0,32,01-01-2017,32,03-01-2017,32,1292103,1669280,196476,298060,Yes,AVAILABLE,32,32,MORE STORIES HUEY TELLS,0,28-02-2018 12:00,M164422,2.0,1,0,28-11-2015 12:00,2017,Kids,1
276,4.000000e+13,32,AECS Layout,01-01-2017 08:01,01-01-2017 08:01,BOOK,0,32,01-01-2017,32,03-01-2017,32,1330795,1663406,186893,288251,Yes,AVAILABLE,32,32,NODDY AND HIS CAR---3,0,21-12-2017 12:00,M174600,2.0,1,500,21-04-2016 12:00,2017,Kids,1
277,4.000000e+13,32,AECS Layout,01-01-2017 12:29,01-01-2017 12:29,BOOK,0,32,01-01-2017,32,08-01-2017,32,38286,1647370,194902,282879,Yes,AVAILABLE,32,32,LISTEN UP! (STEP 3),1,05-04-2020 12:00,M032714,2.0,0,500,03-05-2011 12:00,2017,Kids,1
278,4.000000e+13,32,AECS Layout,01-01-2017 03:33,01-01-2017 03:33,BOOK,0,32,01-01-2017,32,28-05-2017,32,1171053,1645445,215272,281186,Yes,AVAILABLE,32,32,I CAN FLY,1,29-02-2020 17:40,M125477,6.0,0,0,25-01-2014 12:00,2017,Kids,1
279,4.000000e+13,32,AECS Layout,01-01-2017 12:29,01-01-2017 12:29,BOOK,0,32,01-01-2017,32,08-01-2017,32,38286,1644765,195835,279202,Yes,AVAILABLE,32,32,THE FIRST THANKSGIVING (STEP 3),1,05-04-2020 12:00,M032714,2.0,0,500,03-05-2011 12:00,2017,Kids,1
280,4.000000e+13,32,AECS Layout,01-01-2017 07:16,01-01-2017 07:16,BOOK,0,32,01-01-2017,32,11-01-2017,32,1452573,1568227,192157,212107,Yes,AVAILABLE,32,32,PHONICS 6 : FRANK'S FROCK,1,31-01-2021 19:32,M183252,2.0,0,0,27-11-2016 12:00,2017,Kids,1
281,4.000000e+13,32,AECS Layout,01-01-2017 12:11,01-01-2017 12:11,BOOK,0,32,01-01-2017,32,03-01-2017,32,1138727,1675916,194602,175878,Yes,RENTED,32,32,HORRIBLE GEOGRAPHY: CRACKING COASTS,0,09-10-2017 12:00,M113494,10.0,0,0,09-08-2013 12:00,2017,Teens,1
282,4.000000e+13,32,AECS Layout,01-01-2017 07:33,01-01-2017 07:33,BOOK,0,32,01-01-2017,32,17-01-2017,32,1118919,414974,196319,126222,Yes,AVAILABLE,962,32,MSB : SCIENCE CHAPTER BOOK #14 ELECTRIC STORM,0,08-09-2021 00:00,M104864,2.0,0,500,09-05-2013 12:00,2017,Kids,1
283,4.000000e+13,32,AECS Layout,01-01-2017 06:13,01-01-2017 06:13,BOOK,0,32,01-01-2017,32,07-01-2017,32,1029920,389960,192643,100290,Yes,RENTED,32,32,THE FELUDA MYSTERIES: A BAGFUL OF MYSTERY,1,12-04-2023 17:33,M183262,2.0,0,0,25-03-2012 12:00,2017,Teens,1
284,4.000000e+13,32,AECS Layout,01-01-2017 12:11,01-01-2017 12:11,BOOK,0,32,01-01-2017,32,03-01-2017,32,1138727,12808,194605,12808,Yes,TRANSIT,32,32,HORRIBLE GEOGRAPHY: FREAKY PEAKS,0,09-10-2017 12:00,M113494,10.0,0,0,09-08-2013 12:00,2017,Teens,1
289,4.000000e+13,37,Mysore Kalidasa Road,01-01-2017 11:40,01-01-2017 11:40,BOOK,0,37,01-01-2017,37,08-01-2017,37,37240,3978331,350353,848696,Yes,RENTED,1008,37,THE MOTHER I NEVER KNEW,1,24-12-2019 12:00,M030740,3.0,0,750,22-04-2011 12:00,2017,Non Fiction,1
290,4.000000e+13,37,Mysore Kalidasa Road,01-01-2017 11:03,01-01-2017 11:03,BOOK,0,37,01-01-2017,37,08-01-2017,37,51865,4112991,278285,967443,Yes,AVAILABLE,37,37,"SHE BROKE UP, DIDN'T !",1,09-01-2019 12:00,M040841,2.0,0,500,27-08-2011 12:00,2017,Non Fiction,1
291,4.000000e+13,37,Mysore Kalidasa Road,01-01-2017 11:03,01-01-2017 11:03,BOOK,0,37,01-01-2017,37,08-01-2017,37,51865,4112989,274740,967438,Yes,AVAILABLE,37,37,YOU WERE MY CRUSH!,1,09-01-2019 12:00,M040841,2.0,0,500,27-08-2011 12:00,2017,Fiction,1
292,4.000000e+13,37,Mysore Kalidasa Road,01-01-2017 05:01,01-01-2017 05:01,BOOK,0,37,01-01-2017,37,19-01-2017,37,1010529,4151500,403600,1000072,Yes,AVAILABLE,37,37,ORDER TO KILL,1,27-01-2020 12:00,M059206,4.0,2,0,25-12-2011 12:00,2017,Fiction,1
293,4.000000e+13,37,Mysore Kalidasa Road,01-01-2017 05:07,01-01-2017 05:07,BOOK,0,37,01-01-2017,37,15-01-2017,37,1020909,4139933,400947,994114,Yes,AVAILABLE,37,37,THE SECRET BENEATH THE VEIL(M&B SEP'16)MODERN,1,09-05-2020 16:30,M062706,2.0,1,500,09-02-2012 12:00,2017,Fiction,1
294,4.000000e+13,37,Mysore Kalidasa Road,01-01-2017 04:41,01-01-2017 04:41,BOOK,0,37,01-01-2017,37,13-01-2017,37,1142651,4130838,386192,980857,Yes,RENTED,37,37,THE BACHELOR,1,13-12-2022 17:15,M115924,2.0,0,250,27-08-2013 12:00,2017,Fiction,1
295,4.000000e+13,47,Mysore Kalidasa Road,01-01-2017 05:43,01-01-2017 05:43,BOOK,0,47,01-01-2017,47,10-01-2017,47,1028079,4130830,386192,980862,Yes,AVAILABLE,37,37,THE BACHELOR,0,17-07-2018 12:00,M107219,2.0,1,0,17-03-2012 12:00,2017,Fiction,1
296,4.000000e+13,37,Mysore Kalidasa Road,01-01-2017 05:19,01-01-2017 05:19,BOOK,0,37,01-01-2017,37,04-01-2017,37,1222154,4154867,409764,1006020,Yes,AVAILABLE,37,37,THE BABY PROPOSAL (M&B DEC'16) DESIRE,1,24-01-2020 14:33,M138836,2.0,0,500,30-09-2014 12:00,2017,Fiction,1
297,4.000000e+13,37,Mysore Kalidasa Road,01-01-2017 11:10,01-01-2017 11:10,BOOK,0,37,01-01-2017,37,10-01-2017,37,1134926,4152590,403806,1003996,Yes,AVAILABLE,37,37,THE SPY,1,23-02-2020 12:00,M106895,2.0,0,500,21-07-2013 12:00,2017,Non Fiction,1
298,4.000000e+13,47,Mysore Kalidasa Road,01-01-2017 02:47,01-01-2017 02:47,BOOK,0,47,01-01-2017,47,13-01-2017,47,1361484,3980408,351519,850091,Yes,AVAILABLE,37,37,PERCY JACKSON AND THE GREEK GODS,0,18-01-2018 12:00,M175212,2.0,0,500,19-06-2016 12:00,2017,Teens,1
299,4.000000e+13,37,Mysore Kalidasa Road,01-01-2017 03:05,01-01-2017 03:05,BOOK,0,37,01-01-2017,37,05-01-2017,37,1466474,4039344,271461,899587,Yes,AVAILABLE,37,37,VOL 57 TOUCH OF STONE,1,27-05-2024 07:05,M184086,3.0,0,750,01-01-2017 12:00,2017,Kids,1
300,4.000000e+13,37,Mysore Kalidasa Road,01-01-2017 05:10,01-01-2017 05:10,BOOK,0,37,01-01-2017,37,11-01-2017,37,1452724,4152431,403667,1002349,Yes,AVAILABLE,37,37,MAGICAL MISSION,1,05-12-2021 13:28,M178193,4.0,0,0,27-11-2016 12:00,2017,Kids,1
302,4.000000e+13,37,Mysore Kalidasa Road,01-01-2017 05:10,01-01-2017 05:10,BOOK,0,37,01-01-2017,37,11-01-2017,37,1452724,4033424,196129,895339,Yes,AVAILABLE,37,37,THE MUMMY WITH NO NAME,1,05-12-2021 13:28,M178193,4.0,0,0,27-11-2016 12:00,2017,Teens,1
303,4.000000e+13,37,Mysore Kalidasa Road,01-01-2017 05:04,01-01-2017 05:04,BOOK,0,37,01-01-2017,37,15-01-2017,37,1020909,3912789,330133,798571,Yes,AVAILABLE,37,37,A PRICE WORTH PAYING?(M&B MAY 13),1,09-05-2020 16:30,M062706,2.0,1,500,09-02-2012 12:00,2017,Fiction,1
304,4.000000e+13,37,Mysore Kalidasa Road,01-01-2017 05:08,01-01-2017 05:08,BOOK,0,37,01-01-2017,37,11-01-2017,37,1286553,4051558,256718,910570,Yes,AVAILABLE,37,37,JODI HAKKI HAARITU,1,31-12-2020 14:02,M162405,2.0,0,0,09-10-2015 12:00,2017,Non Fiction,1
329,4.000000e+13,37,Mysore Kalidasa Road,01-01-2017 12:08,01-01-2017 12:08,BOOK,0,37,01-01-2017,37,09-05-2017,37,1441426,3744622,254232,670044,Yes,AVAILABLE,37,37,THE BEST OF AKBAR BIRBAL,1,22-12-2024 15:24,M178188,2.0,0,500,18-11-2016 12:00,2017,Kids,1
330,4.000000e+13,37,Mysore Kalidasa Road,01-01-2017 01:15,01-01-2017 01:15,BOOK,0,37,01-01-2017,37,25-02-2017,37,50194,3764474,192761,685052,Yes,AVAILABLE,37,37,NANCY DREW 09 : THE SIGN OF THE TWISTED,1,04-05-2020 15:34,M040800,1.0,0,500,07-08-2011 12:00,2017,Teens,1
331,4.000000e+13,37,Mysore Kalidasa Road,01-01-2017 01:14,01-01-2017 01:14,BOOK,0,37,01-01-2017,47,17-01-2017,37,1108692,3670516,245914,597831,Yes,Q,17,37,THE HYPNOTIST,1,30-12-2019 13:28,M093534,4.0,0,0,28-03-2013 12:00,2017,Non Fiction,1
332,4.000000e+13,37,Mysore Kalidasa Road,01-01-2017 11:40,01-01-2017 11:40,BOOK,0,37,01-01-2017,37,08-01-2017,37,37240,3563857,227830,500078,Yes,AVAILABLE,37,37,REBECCA,1,24-12-2019 12:00,M030740,3.0,0,750,22-04-2011 12:00,2017,Fiction,1
333,4.000000e+13,37,Mysore Kalidasa Road,01-01-2017 02:53,01-01-2017 02:53,BOOK,0,37,01-01-2017,37,18-01-2017,37,1296965,1765462,193826,374383,Yes,AVAILABLE,37,37,THE 3 MISTAKES OF MY LIFE,1,03-04-2023 10:48,M166772,1.0,0,500,05-01-2016 12:00,2017,Non Fiction,1
337,4.000000e+13,37,Mysore Kalidasa Road,01-01-2017 11:40,01-01-2017 11:40,BOOK,0,37,01-01-2017,37,15-01-2017,37,37240,1767279,187283,366290,Yes,RENTED,45,37,CHASING THE DIME (A): 12,1,24-12-2019 12:00,M030740,3.0,0,750,22-04-2011 12:00,2017,Fiction,1
338,4.000000e+13,37,Mysore Kalidasa Road,01-01-2017 03:41,01-01-2017 03:41,BOOK,0,37,01-01-2017,37,21-01-2017,37,1233523,1767194,203191,366161,Yes,AVAILABLE,37,37,BLOODLINE,1,28-11-2021 12:00,M192198,2.0,0,0,21-11-2014 12:00,2017,Non Fiction,1
339,4.000000e+13,37,Mysore Kalidasa Road,01-01-2017 11:55,01-01-2017 11:55,BOOK,0,37,01-01-2017,37,21-01-2017,37,1220865,1763532,196014,372132,Yes,AVAILABLE,37,37,HORRIBLE HISTORIES: CUT-THROAT CELTS,0,30-07-2020 12:00,M138834,2.0,0,500,25-09-2014 12:00,2017,Teens,1
340,4.000000e+13,37,Mysore Kalidasa Road,01-01-2017 11:55,01-01-2017 11:55,BOOK,0,37,01-01-2017,37,21-01-2017,37,1220865,1650784,197397,281241,Yes,RENTED,52,37,THE TALKING T. REX,0,30-07-2020 12:00,M138834,2.0,0,500,25-09-2014 12:00,2017,Kids,1
341,4.000000e+13,37,Mysore Kalidasa Road,01-01-2017 03:05,01-01-2017 03:05,BOOK,0,37,01-01-2017,37,10-01-2017,37,1466474,1789656,177161,390231,Yes,AVAILABLE,37,37,YASHASSINATTA PAYANA,1,27-05-2024 07:05,M184086,3.0,0,750,01-01-2017 12:00,2017,Non Fiction,1
342,4.000000e+13,37,Mysore Kalidasa Road,01-01-2017 03:41,01-01-2017 03:41,BOOK,0,37,01-01-2017,37,04-01-2017,37,1233523,3459422,192668,439712,Yes,AVAILABLE,37,37,THOUSAND SPLENDID SUNS,1,28-11-2021 12:00,M192198,2.0,0,0,21-11-2014 12:00,2017,Non Fiction,1
343,4.000000e+13,47,Mysore Kalidasa Road,01-01-2017 12:42,01-01-2017 12:42,BOOK,0,47,01-01-2017,47,03-01-2017,47,1461287,3513397,211435,480835,Yes,AVAILABLE,37,37,KADHAL ORUVANAIK KAIPPIDITTHEN,0,21-09-2018 12:00,M182843,3.0,0,500,23-12-2016 12:00,2017,Non Fiction,1
344,4.000000e+13,37,Mysore Kalidasa Road,01-01-2017 05:08,01-01-2017 05:08,BOOK,0,37,01-01-2017,37,11-01-2017,37,1286553,3513412,211581,480897,Yes,AVAILABLE,37,37,UNNITATTHIL ENNAIK KODUTTHEN!,1,31-12-2020 14:02,M162405,2.0,0,0,09-10-2015 12:00,2017,Non Fiction,1
345,4.000000e+13,47,Mysore Kalidasa Road,01-01-2017 12:42,01-01-2017 12:42,BOOK,0,47,01-01-2017,47,03-01-2017,47,1461287,3513399,211599,480832,Yes,AVAILABLE,37,37,VAZHVENPADU UNNODUTHAN,0,21-09-2018 12:00,M182843,3.0,0,500,23-12-2016 12:00,2017,Non Fiction,1
346,4.000000e+13,37,Mysore Kalidasa Road,01-01-2017 03:05,01-01-2017 03:05,BOOK,0,37,01-01-2017,37,05-01-2017,37,1466474,3496811,196318,463137,Yes,AVAILABLE,37,37,MSB : SCIENCE CHAPTER BOOK #06 THE GIANT GERM,1,27-05-2024 07:05,M184086,3.0,0,750,01-01-2017 12:00,2017,Kids,1
347,4.000000e+13,37,Mysore Kalidasa Road,01-01-2017 01:14,01-01-2017 01:14,BOOK,0,37,01-01-2017,47,17-01-2017,37,1108692,1762162,191525,371467,Yes,Q,37,37,FAME,1,30-12-2019 13:28,M093534,4.0,0,0,28-03-2013 12:00,2017,Non Fiction,1
352,4.000000e+13,37,Mysore Kalidasa Road,01-01-2017 02:21,01-01-2017 02:21,BOOK,0,37,01-01-2017,37,18-01-2017,37,1296965,1774228,190119,376431,Yes,AVAILABLE,37,37,THE CIRCUS OF ADVENTURE,1,03-04-2023 10:48,M166772,1.0,0,500,05-01-2016 12:00,2017,Teens,1
353,4.000000e+13,37,Mysore Kalidasa Road,01-01-2017 02:55,01-01-2017 02:55,BOOK,0,37,01-01-2017,37,03-01-2017,37,1227613,1774034,189812,376488,Yes,AVAILABLE,37,37,STINK INCREDIBLE SUPERGALACTIC,1,11-02-2021 19:49,M141410,2.0,0,500,22-10-2014 12:00,2017,Kids,1
354,4.000000e+13,37,Mysore Kalidasa Road,01-01-2017 01:14,01-01-2017 01:14,BOOK,0,37,01-01-2017,47,17-01-2017,37,1108692,1774568,189291,377350,Yes,AVAILABLE,37,37,DOUBLE WHAMMY,1,30-12-2019 13:28,M093534,4.0,0,0,28-03-2013 12:00,2017,Non Fiction,1
456,4.000000e+13,3,Justbooks Buglerock,01-01-2017 08:01,01-01-2017 08:01,BOOK,0,3,01-01-2017,3,08-01-2017,3,1185482,3999916,356023,865622,Yes,TRANSIT,3,62,THE LONG HAUL - DIARY OF A WIMPY KID #9,1,12-04-2020 12:00,M129611,2.0,0,500,09-04-2014 12:00,2017,Teens,1
545,4.000000e+13,350,MASTER WAREHOUSE-2,02-01-2017 01:44,02-01-2017 01:44,BOOK,0,350,02-01-2017,350,03-01-2017,350,1429584,3671822,193902,599323,Yes,TRANSIT,962,962,MICE ARE NICE (STEP 2),0,22-10-2017 12:00,M178699,2.0,0,0,22-10-2016 12:00,2017,Kids,1
548,4.000000e+13,350,MASTER WAREHOUSE-2,02-01-2017 12:46,02-01-2017 12:46,BOOK,0,350,02-01-2017,350,12-01-2017,350,1433830,1565456,245490,211611,Yes,TRANSIT,962,962,RAMAYANA - THE GREAT INDIAN EPIC,0,03-05-2017 12:00,M178713,2.0,0,0,03-11-2016 12:00,2017,Teens,1
552,4.000000e+13,350,MASTER WAREHOUSE-2,02-01-2017 12:58,02-01-2017 12:58,BOOK,0,350,02-01-2017,350,04-01-2017,350,1400624,4122744,352880,975638,Yes,TRANSIT,962,962,THE MYSTERY IN THE FORBIDDEN CITY (ENGLISH),0,01-08-2017 12:00,M178667,2.0,0,0,01-08-2016 12:00,2017,Kids,1
553,4.000000e+13,350,MASTER WAREHOUSE-2,02-01-2017 01:04,02-01-2017 01:04,BOOK,0,350,02-01-2017,350,10-01-2017,350,1426430,4122691,372904,975298,Yes,TRANSIT,962,962,HUMAN BODY-KNOWLEDGE BOOK,0,04-10-2017 12:00,M178694,2.0,0,0,04-10-2016 12:00,2017,Kids,1
556,4.000000e+13,350,MASTER WAREHOUSE-2,02-01-2017 12:36,02-01-2017 12:36,BOOK,0,350,02-01-2017,350,30-01-2017,350,1400724,4122567,293532,975244,Yes,TRANSIT,962,962,INVENTIONS AND DISCOVERIES,0,01-08-2017 12:00,M178669,2.0,0,0,01-08-2016 12:00,2017,Kids,1
557,4.000000e+13,350,MASTER WAREHOUSE-2,02-01-2017 01:09,02-01-2017 01:09,BOOK,0,350,02-01-2017,350,05-01-2017,350,1403324,4122078,352797,974852,Yes,RENTED,962,962,SEVEN O'CLOCK TALES,0,08-08-2017 12:00,M178679,2.0,0,0,08-08-2016 12:00,2017,Kids,1
562,4.000000e+13,16,MASTER WAREHOUSE-2,02-01-2017 06:53,02-01-2017 06:53,BOOK,0,16,02-01-2017,16,23-01-2017,16,1157415,3957767,197267,833085,Yes,RENTED,962,962,CAPTAIN UNDERPANTS: THE PERILOUS PLOT OF PROFESSO,0,15-03-2018 12:00,M119956,2.0,0,500,15-11-2013 12:00,2017,Teens,1
563,4.000000e+13,16,MASTER WAREHOUSE-2,02-01-2017 04:08,02-01-2017 04:08,BOOK,0,16,02-01-2017,16,22-03-2017,16,1122534,3955447,343740,831108,Yes,TRANSIT,962,962,PERCY JACKSON (3) : THE TITAN'S CURSE,0,21-03-2018 12:00,M108149,3.0,0,250,21-05-2013 12:00,2017,Teens,1
640,4.000000e+13,350,AECS Layout,02-01-2017 12:43,02-01-2017 12:43,BOOK,0,350,02-01-2017,350,04-01-2017,350,1371424,4081141,357433,939034,Yes,AVAILABLE,32,32,MOUSEFORD ACADEMY - MOUSELETS IN DANGER,0,06-07-2017 12:00,M178657,2.0,0,500,06-07-2016 12:00,2017,Kids,1
645,4.000000e+13,32,AECS Layout,03-01-2017 03:15,03-01-2017 03:15,BOOK,0,32,03-01-2017,32,25-02-2017,32,1316384,1813033,193994,420543,Yes,AVAILABLE,32,32,SECRETS OF DROON #15 THE MOON SCROLL,0,17-12-2017 12:00,M170487,2.0,0,500,25-03-2016 12:00,2017,Teens,1
646,4.000000e+13,32,AECS Layout,03-01-2017 01:44,03-01-2017 01:44,BOOK,0,32,03-01-2017,32,04-01-2017,32,1330795,1770104,196138,368453,Yes,RENTED,32,32,A FABUMOUSE SCHOOL ADVENTURE,0,21-12-2017 12:00,M174600,2.0,1,500,21-04-2016 12:00,2017,Teens,1
650,4.000000e+13,32,AECS Layout,03-01-2017 11:14,03-01-2017 11:14,BOOK,0,32,03-01-2017,32,04-01-2017,32,1380080,12870,198181,12870,Yes,AVAILABLE,32,32,MYSTERY OF THE SCREAMING CLOCK,0,13-08-2017 12:00,M173940,2.0,1,500,13-07-2016 12:00,2017,Kids,1